### Create a new report
POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "Toyota",
  "model": "Corolla",
  "year": 2019,
  "price": 20000,
  "mileage": 10000,
  "lng": -122.084,
  "lat": 37.422
}


### Approve an existing report
PATCH http://localhost:3000/reports/6
Content-Type: application/json

{
  "approved": true
}

### Get an Estimate for an existing vehicle

GET http://localhost:3000/reports?make=Ford&model=Corolla&year=2019&mileage=10000&lng=-122.084&lat=37.422
