###  Create a new User

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "harrie@gmail.com",
    "password": "labalqbq"
}

###  Sign In

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "harrie@gmail.com",
    "password": "labalqbq"
}


### Find a particular user
GET http://localhost:3000/auth/4


### Find all users with a given email
GET http://localhost:3000/auth?email=harrie@gmail.com



### Update a user with a given id
PATCH http://localhost:3000/auth/4
Content-Type: application/json

{
    "password": "123456"
}

#### Delete a user with a given id
DELETE http://localhost:3000/auth/5

### Get CurrentUser
GET http://localhost:3000/auth/currentUser

### Sign Out
POST http://localhost:3000/auth/signout
